
package com.temenos.wsbanescobcon;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.temenos.buildcontrol.BUILDCONTROLType;
import com.temenos.buildcontrolerrors.BUILDCONTROLERRORSType;
import com.temenos.buildcontrolresults.BUILDCONTROLRESULTSType;
import java.util.concurrent.Future;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "T24WebServicesImpl", targetNamespace = "http://temenos.com/WSBanescoBCON")
@XmlSeeAlso({
    com.temenos.buildcontrolerrors.ObjectFactory.class,
    com.temenos.buildcontrolresults.ObjectFactory.class,
    com.temenos.buildcontrol.ObjectFactory.class,
    com.temenos.wsbanescobcon.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface T24WebServicesImpl {


    /**
     * 
     * @param ofsResponse
     * @param ofsRequest
     * @param status
     */
    @WebMethod
    @RequestWrapper(localName = "callOfs", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.CallOfs")
    @ResponseWrapper(localName = "callOfsResponse", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.CallOfsResponse")
    @Action(input = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/callOfsRequest", output = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/callOfsResponse")
    public void callOfs(
        @WebParam(name = "OfsRequest", targetNamespace = "")
        String ofsRequest,
        @WebParam(name = "Status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Status> status,
        @WebParam(name = "OfsResponse", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> ofsResponse);

    /**
     * 
     * @param webRequestCommon
     * @param buildcontrolType
     * @param buildcontrolType0
     * @param status
     */
    @WebMethod(operationName = "CreateBconPhysicUnit")
    @RequestWrapper(localName = "CreateBconPhysicUnit", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.CreateBconPhysicUnit")
    @ResponseWrapper(localName = "CreateBconPhysicUnitResponse", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.CreateBconPhysicUnitResponse")
    @Action(input = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/CreateBconPhysicUnitRequest", output = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/CreateBconPhysicUnitResponse")
    public void createBconPhysicUnit(
        @WebParam(name = "WebRequestCommon", targetNamespace = "")
        WebRequestCommon webRequestCommon,
        @WebParam(name = "BUILDCONTROLType", targetNamespace = "")
        TransactionId buildcontrolType,
        @WebParam(name = "Status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Status> status,
        @WebParam(name = "BUILDCONTROLType", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<BUILDCONTROLType> buildcontrolType0);

    /**
     * 
     * @param webRequestCommon
     * @param buildcontrolType
     * @param buildcontrolType0
     * @param status
     */
   /* @WebMethod(operationName = "ReverseBconatAppLevel")
    @RequestWrapper(localName = "ReverseBconatAppLevel", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.ReverseBconatAppLevel")
    @ResponseWrapper(localName = "ReverseBconatAppLevelResponse", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.ReverseBconatAppLevelResponse")
    @Action(input = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/ReverseBconatAppLevelRequest", output = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/ReverseBconatAppLevelResponse")
    public void reverseBconatAppLevel(
        @WebParam(name = "WebRequestCommon", targetNamespace = "")
        WebRequestCommon webRequestCommon,
        @WebParam(name = "BUILDCONTROLType", targetNamespace = "")
        TransactionId buildcontrolType,
        @WebParam(name = "Status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Status> status,
        @WebParam(name = "BUILDCONTROLType", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<BUILDCONTROLType> buildcontrolType0);*/

    /**
     * 
     * @param webRequestCommon
     * @param buildcontrolerrorsType
     * @param status
     * @param buildcontrolerrorsType0
     */
   /* @WebMethod(operationName = "ViewtheErrorsofaBCONunit")
    @RequestWrapper(localName = "ViewtheErrorsofaBCONunit", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.ViewtheErrorsofaBCONunit")
    @ResponseWrapper(localName = "ViewtheErrorsofaBCONunitResponse", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.ViewtheErrorsofaBCONunitResponse")
    @Action(input = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/ViewtheErrorsofaBCONunitRequest", output = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/ViewtheErrorsofaBCONunitResponse")
    public void viewtheErrorsofaBCONunit(
        @WebParam(name = "WebRequestCommon", targetNamespace = "")
        WebRequestCommon webRequestCommon,
        @WebParam(name = "BUILDCONTROLERRORSType", targetNamespace = "")
        EnquiryInput buildcontrolerrorsType,
        @WebParam(name = "Status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Status> status,
        @WebParam(name = "BUILDCONTROLERRORSType", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<BUILDCONTROLERRORSType>> buildcontrolerrorsType0);*/

    /**
     * 
     * @param webRequestCommon
     * @param buildcontrolresultsType
     * @param status
     * @param buildcontrolresultsType0
     */
    @WebMethod(operationName = "ViewtheResultsofaBCONunit")
    @RequestWrapper(localName = "ViewtheResultsofaBCONunit", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.ViewtheResultsofaBCONunit")
    @ResponseWrapper(localName = "ViewtheResultsofaBCONunitResponse", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.ViewtheResultsofaBCONunitResponse")
    @Action(input = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/ViewtheResultsofaBCONunitRequest", output = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/ViewtheResultsofaBCONunitResponse")
    public void viewtheResultsofaBCONunit(
        @WebParam(name = "WebRequestCommon", targetNamespace = "")
        WebRequestCommon webRequestCommon,
        @WebParam(name = "BUILDCONTROLRESULTSType", targetNamespace = "")
        EnquiryInput buildcontrolresultsType,
        @WebParam(name = "Status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Status> status,
        @WebParam(name = "BUILDCONTROLRESULTSType", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<BUILDCONTROLRESULTSType>> buildcontrolresultsType0);

    /**
     * 
     * @param webRequestCommon
     * @param ofsFunction
     * @param buildcontrolType
     * @param status
     */
    @WebMethod(operationName = "CreateT24BconUnit")
    @RequestWrapper(localName = "CreateT24BconUnit", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.CreateT24BconUnit")
    @ResponseWrapper(localName = "CreateT24BconUnitResponse", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.CreateT24BconUnitResponse")
    @Action(input = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/CreateT24BconUnitRequest", output = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/CreateT24BconUnitResponse")
    public void createT24BconUnit(
        @WebParam(name = "WebRequestCommon", targetNamespace = "")
        WebRequestCommon webRequestCommon,
        @WebParam(name = "OfsFunction", targetNamespace = "")
        OfsFunction ofsFunction,
        @WebParam(name = "BUILDCONTROLType", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<BUILDCONTROLType> buildcontrolType,
        @WebParam(name = "Status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Status> status);

    /**
     * 
     * @param webRequestCommon
     * @param ofsFunction
     * @param buildcontrolType
     * @param status
     */
    @WebMethod(operationName = "CreateT24BconUnit_Validate")
    @RequestWrapper(localName = "CreateT24BconUnit_Validate", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.CreateT24BconUnitValidate")
    @ResponseWrapper(localName = "CreateT24BconUnit_ValidateResponse", targetNamespace = "http://temenos.com/WSBanescoBCON", className = "com.temenos.wsbanescobcon.CreateT24BconUnitValidateResponse")
    @Action(input = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/CreateT24BconUnit_ValidateRequest", output = "http://temenos.com/WSBanescoBCON/T24WebServicesImpl/CreateT24BconUnit_ValidateResponse")
    public void createT24BconUnitValidate(
        @WebParam(name = "WebRequestCommon", targetNamespace = "")
        WebRequestCommon webRequestCommon,
        @WebParam(name = "OfsFunction", targetNamespace = "")
        OfsFunction ofsFunction,
        @WebParam(name = "BUILDCONTROLType", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<BUILDCONTROLType> buildcontrolType,
        @WebParam(name = "Status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Status> status);
    
    
    
  @WebMethod(operationName="ViewtheErrorsofaBCONunit")
  @RequestWrapper(localName="ViewtheErrorsofaBCONunit", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ViewtheErrorsofaBCONunit")
  @ResponseWrapper(localName="ViewtheErrorsofaBCONunitResponse", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ViewtheErrorsofaBCONunitResponse")
  public abstract Response<ViewtheErrorsofaBCONunitResponse> viewtheErrorsofaBCONunitAsync(@WebParam(name="WebRequestCommon", targetNamespace="") WebRequestCommon paramWebRequestCommon, @WebParam(name="BUILDCONTROLERRORSType", targetNamespace="") EnquiryInput paramEnquiryInput, @WebParam(name="Status", targetNamespace="", mode=WebParam.Mode.OUT) Holder<Status> paramHolder, @WebParam(name="BUILDCONTROLERRORSType", targetNamespace="", mode=WebParam.Mode.OUT) Holder<List<BUILDCONTROLERRORSType>> paramHolder1);
  
  @WebMethod(operationName="ViewtheErrorsofaBCONunit")
  @RequestWrapper(localName="ViewtheErrorsofaBCONunit", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ViewtheErrorsofaBCONunit")
  @ResponseWrapper(localName="ViewtheErrorsofaBCONunitResponse", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ViewtheErrorsofaBCONunitResponse")
  public abstract Future<?> viewtheErrorsofaBCONunitAsync(@WebParam(name="WebRequestCommon", targetNamespace="") WebRequestCommon paramWebRequestCommon, @WebParam(name="BUILDCONTROLERRORSType", targetNamespace="") EnquiryInput paramEnquiryInput, @WebParam(name="asyncHandler", targetNamespace="") AsyncHandler<ViewtheErrorsofaBCONunitResponse> paramAsyncHandler);
  
  @WebMethod(operationName="ViewtheErrorsofaBCONunit")
  @RequestWrapper(localName="ViewtheErrorsofaBCONunit", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ViewtheErrorsofaBCONunit")
  @ResponseWrapper(localName="ViewtheErrorsofaBCONunitResponse", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ViewtheErrorsofaBCONunitResponse")
  @Action(input="http://temenos.com/WSBanescoBCON/T24WebServicesImpl/ViewtheErrorsofaBCONunitRequest", output="http://temenos.com/WSBanescoBCON/T24WebServicesImpl/ViewtheErrorsofaBCONunitResponse")
  public abstract void viewtheErrorsofaBCONunit(@WebParam(name="WebRequestCommon", targetNamespace="") WebRequestCommon paramWebRequestCommon, @WebParam(name="BUILDCONTROLERRORSType", targetNamespace="") EnquiryInput paramEnquiryInput, @WebParam(name="Status", targetNamespace="", mode=WebParam.Mode.OUT) Holder<Status> paramHolder, @WebParam(name="BUILDCONTROLERRORSType", targetNamespace="", mode=WebParam.Mode.OUT) Holder<List<BUILDCONTROLERRORSType>> paramHolder1);
  
  /****************************************************************/
    
   @WebMethod(operationName="ReverseBconatAppLevel")
  @RequestWrapper(localName="ReverseBconatAppLevel", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ReverseBconatAppLevel")
  @ResponseWrapper(localName="ReverseBconatAppLevelResponse", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ReverseBconatAppLevelResponse")
  public abstract Response<ReverseBconatAppLevelResponse> reverseBconatAppLevelAsync(@WebParam(name="WebRequestCommon", targetNamespace="") WebRequestCommon paramWebRequestCommon, @WebParam(name="BUILDCONTROLType", targetNamespace="") TransactionId buildcontrolType);
  
  @WebMethod(operationName="ReverseBconatAppLevel")
  @RequestWrapper(localName="ReverseBconatAppLevel", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ReverseBconatAppLevel")
  @ResponseWrapper(localName="ReverseBconatAppLevelResponse", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ReverseBconatAppLevelResponse")
  public abstract Future<?> reverseBconatAppLevelAsync(@WebParam(name="WebRequestCommon", targetNamespace="") WebRequestCommon paramWebRequestCommon, @WebParam(name="BUILDCONTROLType", targetNamespace="") TransactionId buildcontrolType, @WebParam(name="asyncHandler", targetNamespace="") AsyncHandler<ReverseBconatAppLevelResponse> paramAsyncHandler);
  
  @WebMethod(operationName="ReverseBconatAppLevel")
  @RequestWrapper(localName="ReverseBconatAppLevel", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ReverseBconatAppLevel")
  @ResponseWrapper(localName="ReverseBconatAppLevelResponse", targetNamespace="http://temenos.com/WSBanescoBCON", className="com.temenos.wsbanescobcon.ReverseBconatAppLevelResponse")
  @Action(input="http://temenos.com/WSBanescoBCON/T24WebServicesImpl/ReverseBconatAppLevelRequest", output="http://temenos.com/WSBanescoBCON/T24WebServicesImpl/ReverseBconatAppLevelResponse")
  public abstract void reverseBconatAppLevel(@WebParam(name="WebRequestCommon", targetNamespace="") WebRequestCommon paramWebRequestCommon, @WebParam(name="BUILDCONTROLType", targetNamespace="") TransactionId buildcontrolType, @WebParam(name="Status", targetNamespace="", mode=WebParam.Mode.OUT) Holder<Status> paramHolder, @WebParam(name="BUILDCONTROLType", targetNamespace="", mode=WebParam.Mode.OUT) Holder<List<BUILDCONTROLType>> paramHolder1);
  
  
  
    
    
    

}
